listener 1883
allow_anonymous false

auth_plugin /mosquitto/go-auth.so

auth_opt_backends http

auth_opt_http_host 192.168.178.100
auth_opt_http_port 8000

auth_opt_http_getuser_uri /api/mqtt/auth
auth_opt_http_aclcheck_uri /api/mqtt/acl